//! Category definitions for Linux system cleaning
//!
//! Paths with ~ are resolved at runtime using dirs::home_dir().
//! Categories are built once via LAZY_CATEGORIES.

use std::path::PathBuf;

/// Describes a cleaning category
#[derive(Clone)]
pub struct Category {
    /// Unique key string (used in config, CLI)
    pub key: &'static str,
    /// Human-readable display name
    pub name: &'static str,
    /// Longer description shown in UI
    pub description: &'static str,
    /// Paths to scan for this category (string literals, ~ resolved at runtime)
    pub path_strs: &'static [&'static str],
    /// Whether this category is auto-cleanable by default
    pub auto_cleanable: bool,
    /// Whether root privileges are required
    pub requires_root: bool,
    /// Glob patterns for files to match (if any)
    pub glob_patterns: Option<&'static [&'static str]>,
}

impl Category {
    /// Resolve path strings to actual PathBufs, expanding ~
    pub fn resolve_paths(&self) -> Vec<PathBuf> {
        self.path_strs
            .iter()
            .filter_map(|s| {
                let s = if s.starts_with("~/") {
                    if let Some(home) = dirs::home_dir() {
                        home.join(s.trim_start_matches("~/"))
                    } else {
                        return None;
                    }
                } else {
                    PathBuf::from(*s)
                };
                Some(s)
            })
            .collect()
    }
}

/// Returns all category definitions (static, no runtime resolution)
pub fn all_category_defs() -> &'static [Category] {
    static DEFS: &[Category] = &[
        SNAP_REVISIONS,
        FLATPAK_ORPHANS,
        THUMBNAILS,
        USER_CACHE,
        PACKAGE_CACHE_APT,
        PACKAGE_CACHE_DNF,
        PACKAGE_CACHE_PACMAN,
        JOURNAL_LOGS,
        SYSTEM_LOGS,
        TRASH,
        DOCKER_IMAGES,
        OLD_KERNELS,
        MAIL_ATTACHMENTS,
    ];
    DEFS
}

// ─── Category Definitions (string-based, ~ resolved at runtime) ─────────────

const SNAP_REVISIONS: Category = Category {
    key: "snap-revisions",
    name: "Snap Revisions",
    description: "Old/disabled Snap package revisions. Active snaps are always kept.",
    path_strs: &["/var/lib/snapd/snaps"],
    auto_cleanable: true,
    requires_root: true,
    glob_patterns: None,
};

const FLATPAK_ORPHANS: Category = Category {
    key: "flatpak-orphans",
    name: "Flatpak Orphans",
    description: "Unused Flatpak runtimes and application remnants.",
    path_strs: &["/var/lib/flatpak", "~/.local/share/flatpak"],
    auto_cleanable: true,
    requires_root: false,
    glob_patterns: None,
};

const THUMBNAILS: Category = Category {
    key: "thumbnails",
    name: "Thumbnails",
    description: "Cached thumbnail images generated by file managers.",
    path_strs: &["~/.cache/thumbnails"],
    auto_cleanable: true,
    requires_root: false,
    glob_patterns: None,
};

const USER_CACHE: Category = Category {
    key: "user-cache",
    name: "User Cache",
    description: "Application caches: browsers, pip, npm, conda, go, cargo, yarn.",
    path_strs: &["~/.cache"],
    auto_cleanable: true,
    requires_root: false,
    glob_patterns: None,
};

const PACKAGE_CACHE_APT: Category = Category {
    key: "package-cache-apt",
    name: "APT Package Cache",
    description: "Downloaded .deb packages from apt. Safe to clean — they'll be re-downloaded if needed.",
    path_strs: &["/var/cache/apt"],
    auto_cleanable: true,
    requires_root: true,
    glob_patterns: None,
};

const PACKAGE_CACHE_DNF: Category = Category {
    key: "package-cache-dnf",
    name: "DNF/YUM Package Cache",
    description: "Downloaded RPM packages from DNF/YUM. Safe to clean.",
    path_strs: &["/var/cache/dnf"],
    auto_cleanable: true,
    requires_root: true,
    glob_patterns: None,
};

const PACKAGE_CACHE_PACMAN: Category = Category {
    key: "package-cache-pacman",
    name: "Pacman Package Cache",
    description: "Downloaded .pkg.tar.zst packages from pacman. Safe to clean.",
    path_strs: &["/var/cache/pacman"],
    auto_cleanable: true,
    requires_root: true,
    glob_patterns: None,
};

const JOURNAL_LOGS: Category = Category {
    key: "journal-logs",
    name: "Journal Logs",
    description: "Old systemd journal entries older than 90 days.",
    path_strs: &["/var/log/journal"],
    auto_cleanable: true,
    requires_root: true,
    glob_patterns: None,
};

const SYSTEM_LOGS: Category = Category {
    key: "system-logs",
    name: "System Logs",
    description: "Rotated log files in /var/log. Never touches active logs.",
    path_strs: &["/var/log"],
    auto_cleanable: false, // manual selection only
    requires_root: true,
    glob_patterns: Some(&["*.log", "*.log.old", "*.log.[0-9]", "*.gz"]),
};

const TRASH: Category = Category {
    key: "trash",
    name: "Trash",
    description: "Files in the user Trash directory.",
    path_strs: &["~/.local/share/Trash"],
    auto_cleanable: true,
    requires_root: false,
    glob_patterns: None,
};

const DOCKER_IMAGES: Category = Category {
    key: "docker-images",
    name: "Docker Images",
    description: "Unused Docker images, stopped containers, and dangling volumes.",
    path_strs: &["/var/lib/docker"],
    auto_cleanable: true,
    requires_root: true,
    glob_patterns: None,
};

const OLD_KERNELS: Category = Category {
    key: "old-kernels",
    name: "Old Kernels",
    description: "Old kernel image files in /boot (not the currently running kernel).",
    path_strs: &["/boot"],
    auto_cleanable: false, // manual selection only — too risky for auto
    requires_root: true,
    glob_patterns: Some(&["vmlinuz-*", "initrd.img-*", "System.map-*"]),
};

const MAIL_ATTACHMENTS: Category = Category {
    key: "mail-attachments",
    name: "Mail Attachments",
    description: "Downloaded mail attachments from Thunderbird and other mail clients.",
    path_strs: &["~/.local/share/mail-downloads"],
    auto_cleanable: true,
    requires_root: false,
    glob_patterns: None,
};

/// Categories that require root privilege (for UI grouping)
pub fn root_categories() -> Vec<Category> {
    all_category_defs().iter().filter(|c| c.requires_root).cloned().collect()
}

/// Categories available to non-root users
pub fn user_categories() -> Vec<Category> {
    all_category_defs().iter().filter(|c| !c.requires_root).cloned().collect()
}

/// Hardcoded exclusion list — paths that are NEVER deleted
pub fn EXCLUDED_PREFIXES() -> &'static [&'static str] {
    &["/etc/", "/.ssh/", "/var/lib/systemd/", "/var/lib/dockeroverlay2/", "/var/lib/docker/containers/"]
}

/// Check if a path is in the exclusion list
pub fn is_excluded(path: &PathBuf) -> bool {
    let p = path.to_string_lossy();
    EXCLUDED_PREFIXES().iter().any(|prefix| p.contains(prefix))
}

/// Check if a snap file is disabled (not currently active revision)
pub fn is_disabled_snap(path: &PathBuf) -> bool {
    // Snap files: active snaps are in /var/lib/snapd/snaps/active/
    // Disabled = not in the active subdir. Simplified: check extension
    path.extension().map(|e| e != "snap").unwrap_or(true)
}

/// Check if a kernel file belongs to the running kernel
pub fn is_current_kernel(path: &PathBuf) -> bool {
    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
        // Real impl: compare with `uname -r`
        // Simplified: skip files that could be the running kernel
        name.starts_with("vmlinuz") || name.starts_with("initrd.img")
    } else {
        false
    }
}

/// Check if a flatpak path is an orphan (unused runtime/app)
pub fn is_flatpak_orphan(path: &PathBuf) -> bool {
    let p = path.to_string_lossy();
    p.contains("/runtime/") && !p.contains("active")
}
